### ISSUE TITLE
Printing next version number on pre-push

### ISSUE THREAD

**Issue by trentrand** [semantic-release/commit-analyzer#141]
To increase developers confidence in their versioning, I'd like to setup a Husky "pre-push" hook which prints the next version number to the committer when they're pushing changes to their Git repository.

I'd like this to happen on all branches, but **only** run @semantic-release/commit-analyzer; not of my other plugins.

My initial idea was to override the `plugins` property of my default `release.config.js` Semantic Release configuration file so that it only includes the `@semantic-release/commit-analyzer` plugin; however, this has the issue of requiring me to specify the current branch name with each call.

Is there a better approach towards achieving this result?

**Comment by pvdlg** [comment]
See related semantic-release/semantic-release#753.

Currently semantic-release is aim at only making release and not at being an orchestrator or tool suite for continuous integration. In other words it's a tool aimed at being part of CI workflow not at orchestrating the whole workflow.

The particular feature you are proposing would be problematic in many cases as there is no guarantees when the actual publish occurs the codebase and commit history, will be the same as the ones on the local branch of the developer. So the information displayed has a good change to be inaccurate. Remember that semantic-release will release on your main branch (likely `master`) and that the current local branch might or might not be up to date with `master` when you commit your code.

**Comment by pvdlg** [comment]
Closing as this not something we would implement. But feel free to continue the conversation here.
