### ISSUE TITLE
Does commit-analyzer ignore merge commits?

### ISSUE THREAD

**Issue by samlevin** [semantic-release/commit-analyzer#146]
Interested in adopting semantic-release for a project where all commits follow the angular commit message conventions aside from GitHub merge commits. Will this project be compatible with semantic-release as-is when generating release notes?

**Comment by pvdlg** [comment]
semantic-release care only about commits formatted according to a convention that are in the history of the release branch. But what would you care about the merge commits? They don't carry any relevant code change by themself, they just make commits from a source branch to be part of the history of a target branch.
semantic-release will parse the commit you merge if they are formatted properly.

It's really difficult to answer you when what you want to achieve is so vague and when you don't report an actual problem...Have you even tried to use semantic-release? Maybe try first and report if you encounter an issue.

**Comment by samlevin** [comment]
`semantic-release will parse the commit you merge if they are formatted properly.` this answers my question. thanks for your time
