### ISSUE TITLE
Missing support for releaseRules external module in semantic-release shareable configuration

### ISSUE THREAD

**Issue by skeggse** [semantic-release/commit-analyzer#150]
I've got a shareable `semantic-release` config and want to add `releaseRules`. I figured it'd be neat to put it in a separate file because that's noted in the docs. Unfortunately, it looks like `commit-analyzer` isn't able to resolve the file relative to the shareable configuration - I suspect I'll either need to use `require` or just inline the `releaseRules`.

I imagine we don't really want to have to figure out how to resolve a relative path referenced by a file that we have no easy way to locate, so maybe we could note this limitation in the README.

**Comment by pvdlg** [comment]
You can create your shareable config as a JS file and use require to load your shareable file that contains `releaseRules` with `require`.
The shareable config code is complicated enough and we won't add more complexity to handle those cases.
