### ISSUE TITLE
[Need Help] Include/Map all commits to changelog

### ISSUE THREAD

**Issue by diegolanda** [semantic-release/commit-analyzer#167]
I have a configuration to set default any commit as patch for our current workflow:

```
"release": {
    "npmPublish": false,
    "branches": [
      "master"
    ],
    "plugins": [
      [
        "@semantic-release/commit-analyzer",
        {
          "preset": "angular",
          "releaseRules": [
            {
              "scope": "/.skip ci/",
              "release": false
            },
            {
              "type": "/.*/",
              "release": "patch"
            }
          ]
        }
      ],
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      [
        "@semantic-release/release-notes-generator",
        {
          "host": "https://url.com",
          "linkReferences": false,
          "linkCompare": false
        }
      ],
      [
        "@semantic-release/changelog",
        {
          "changelogTitle": "Changelog"
        }
      ],
      "@semantic-release/git",
      [
        "@semantic-release/exec",
        {
          "successCmd": "command1.sh"
        }
      ],
      [
        "@semantic-release/exec",
        {
          "successCmd": "command2.sh"
        }
      ]
    ]
  }
```

This part is working great but the CHANGELOG is being logged as:

```

## 0.0.11

### Features

* <commit message> hash

## 0.0.10 

## 0.0.9 

```

I couldn't find if this is configurable and include all commits even if they are `chore` `test` `docs`, is there a way to map this as `other` or even to `bugfixes`. 

Is there a way to map/add commits to changelog to avoid having them empty

**Comment by pvdlg** [comment]
`@semantic-release/commit-analyzer` now uses globs instead of regexp.

Please see: https://github.com/semantic-release/commit-analyzer/releases/tag/v7.0.0

**Comment by diegolanda** [comment]
Hi @pvdlg I think I did not make myself clear, I am not using 7 and I am not interested in globs at the moment. Commit-analyzer looks like working fine, but if you check the changelog any `chore:` commits bumps as patched (great) but then in the changelog the commit message is not getting written.

```
## 0.0.11

### Features

* <commit message> hash

## 0.0.10 
<<< Here I would expect my chore commit message
<<< it bumped to 0.0.10 nicely but message is empty once it gets to changelog
## 0.0.9 
```

Do I need v7 to get the changelog updated as well?
