### ISSUE TITLE
How do I lint commits in a PR?

### ISSUE THREAD

**Issue by NullVoxPopuli** [semantic-release/commit-analyzer#170]
I'm using GH actions.
I can get a list of messages different from master.

But how do I fail CI if a commit message isn't in the correct format?

**Comment by travi** [comment]
take a look at [commitlint](https://github.com/conventional-changelog/commitlint). i imagine that's what you're looking for.

in the future, try to post questions like this to [Spectrum](https://github.com/semantic-release/semantic-release#get-help), since there are more people that can help there.
