### ISSUE TITLE
Option to scan tags in other branches

### ISSUE THREAD

**Issue by AndriyGo** [semantic-release/commit-analyzer#176]
In our workflow, we want our releases to progress linearly. For example, `develop` -> `alpha` -> `beta` -> `master`.

Currently, unless we merge changes from `master` all the way back into `alpha` – commit-analyzer will not pick up the latest release which occurred on `master`. So, if we released 1.1.2 on `master` and then add another feature to `alpha` – it would create a 1.1.2-alpha.X pre-release rather than the correct 1.1.3-alpha.1.

I do know that such flow is not very standard, however it works quite well for mobile apps where each staging branch corresponds to a specific stage of testing. Also, given linear one-directional flow, I do not think it makes sense to worry about merging "changes" from `master` all the way back. After all, those changes are due to "merge commits" and tags, none of which make any difference for code integrity.

So, I feel like there should be an option to either scan tags in all branches declared in workflow OR to provide last released version manually.

Is this something that could be considered for a PR? I am aware that it is somewhat against the standard, but I feel like implementing such functionality through an option can only improve `commit-analyzer`.

**Comment by travi** [comment]
I do appreciate you digging deep enough to understand some of the mechanics of what this implementation might take but let's please hold off on cross posting this request until there is some consensus that such functionality is desired. I'm going to close this issue for now, but it could be reopened if we would decide to move forward with this. For now, let's focus the discussion in the [original issue](https://github.com/semantic-release/semantic-release/issues/1603).
