### ISSUE TITLE
Raise the minimum required version of node

### ISSUE THREAD

**Issue by gr2m** [semantic-release/commit-analyzer#244]
Pull request is ready for review: https://github.com/semantic-release/commit-analyzer/pull/248

---

See for reference: https://github.com/semantic-release/semantic-release/issues/2055

- [x] require a minimum node version of the latest LTS, currently 14.17
- [x] ensure `engines-strict` is enforced in the CI of each project to reduce the cases where incompatible dependencies are installed outside of our supported range ([example](https://github.com/semantic-release/semantic-release/blob/88e423b8286cfe852d8348d174e621c1e39e42d8/.github/workflows/test.yml#L36))
- [x] Make sure to update the docs if we mention a minimal node version anywhere

Bonus:

- [x] Make it a native ES Module, but wait until we decided to go with a native ESM module as part of https://github.com/semantic-release/semantic-release/issues/2055

**Pull request welcome!** Just comment below if you'd like to work on it and we will assign the issue to you. Thank you for your help 💐

**Comment by jpedroh** [comment]
Hello!

I'm interested in helping out on this issue :D

**Comment by gr2m** [comment]
Hi @jpedroh, thank you for offering to help! It's all yours! Let us know if you have any questions

**Comment by jpedroh** [comment]
Thanks! Will this follow the same path that is happening in main package? I mean, creating a merge to beta and all?

**Comment by gr2m** [comment]
no need for a beta release, we will only use it in the main `semantic-release` to test the integration of the new plugin versions. For `@semantic-release/commit-analyzer` we can directly release a breaking version to latest

**Comment by jpedroh** [comment]
Great. The node version bump is already completed and is available in #246.

I've also started working on the bonus migration to ES module. The main change is dropping require API (used in import-from) in order to use ESM import API. This introduces a change in `loadReleaseRules` that now returns a promise due to the async nature of import.

https://github.com/jpedroh/commit-analyzer/blob/31869e1799b23b1f2f41c23a6e8c80e5ed35f06e/lib/load-release-rules.js#L20

There's one change to the module's public API though. Because of how imports works in ESM modules, user must insert `.js` at the end of file name to a successfull import.

**Comment by gr2m** [comment]
> I've also started working on the bonus migration to ES module

could you please start a separate pull request for further discussion? I could start the PR on your fork against your `jpedroh:node-14` branch

> There's one change to the module's public API though. Because of how imports works in ESM modules, user must insert `.js` at the end of file name to a successfull import.

You mean for the `releaseNotes` option? I think that's reasonable, we should just mention it in the release notes

<img width="591" alt="image" src="https://user-images.githubusercontent.com/39992/129084347-7b2f8beb-572d-4c25-b2dd-64527189b34f.png">

**Comment by jpedroh** [comment]
> could you please start a separate pull request for further discussion? I could start the PR on your fork against your `jpedroh:node-14` branch

Sure. Just like in core package, I'm making the ESM changes in a separate branch `node-14-esm`. I've opened a PR for it (#247).

> You mean for the `releaseNotes` option? I think that's reasonable, we should just mention it in the release notes
> 
> <img alt="image" width="591" src="https://user-images.githubusercontent.com/39992/129084347-7b2f8beb-572d-4c25-b2dd-64527189b34f.png">

Indeed! What's good is that README already points towards this behavior:
```json
{
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "angular",
      "releaseRules": "./config/release-rules.js"
    }],
    "@semantic-release/release-notes-generator"
  ]
}
```

With the ESM refactor, using `"releaseRules": "./config/release-rules"` would throw an error. Even though the documentation already points it, it might be worth to documentate this behaviour - or perhaps even better, just add the .js at the end of the file.

**Comment by gr2m** [comment]
> Even though the documentation already points it, it might be worth to documentate this behaviour - or perhaps even better, just add the .js at the end of the file.

I think I would just make it explicit in the docs that full path to a `.js` file is required. And mention it in the breaking changes that while it worked before to leave out the `.js` extension or to set the path to a folder with an `index.js` file it no longer will moving forward. I would not add the `.js` extension if it's missing, rather throw a helpful error. It will reduce code complexity and maintenance overhead
