### ISSUE TITLE
Fix "requierable" typos across several places in the code

### ISSUE THREAD

**Issue by gr2m** [semantic-release/commit-analyzer#249]
Replace "Requierable" and "requierable" with "requirable" and "Requirable" respectively

**Comment by himanshu007-creator** [comment]
Hi!, i would like to work on this issue

**Comment by gr2m** [comment]
Thanks Himanshu! I think we got it via https://github.com/semantic-release/commit-analyzer/pull/250, but could you double check?

**Comment by himanshu007-creator** [comment]
> Thanks Himanshu! I think we got it via #250, but could you double check?

Yup, the issue is solved, you can link #250 to this issue and its all sorted

**Comment by gr2m** [comment]
Thanks for checking!
