### ISSUE TITLE
Commit analysis for reverts isn't working as expected

### ISSUE THREAD

**Issue by markrreynolds** [semantic-release/commit-analyzer#323]
I am trying to release 3 commits. I was expecting only the `ghi123` commit to be analyzed for release. This doesn't seem to be how it is working today. Is this supported?

```sh
* ghi123 - feat: thing i really wanted
* def123 - Revert "feat: a thing was done"
* abc123 - feat: a thing was done
```

>If you have a revert commit and the reverted commit within the same release (i.e. between the last release and HEAD) semantic-release will ignore both because as they cancel each other they don't change the code therefore doesn't require a release.

REL: https://github.com/semantic-release/commit-analyzer/issues/84

**Comment by markrzen** [comment]
Based on the unit tests, I suspect the comment is wrong actually. Investigating more on why my commits aren't working.

**Comment by markrreynolds** [comment]
This seems to be caused using `preset: conventionalcommits`. It works properly on `preset: angular`.

**Comment by kevjumba** [comment]
Feast is experiencing the same issues on our release. We accidentally cherry-picked a feat: into the patch release and reverting is not working.

**Comment by markrreynolds** [comment]
We moved to release-please and this issue is no longer relevant for me.
