### ISSUE TITLE
Release type should not be case sensitive

### ISSUE THREAD

**Issue by Laevos** [semantic-release/commit-analyzer#496]
I'm seeing a bug where if a commit is created with the title `Feat:` instead of `feat:`, no release is created. I do see that this is called out, e.g. in [this comment](https://github.com/semantic-release/semantic-release/issues/1949#issuecomment-878589272), but this seems like potentially unexpected behavior. This also seems to go against the language of the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#:~:text=The%20units%20of%20information%20that,a%20token%20in%20a%20footer) spec, which states

> The units of information that make up Conventional Commits MUST NOT be treated as case sensitive by implementors, with the exception of BREAKING CHANGE which MUST be uppercase.

Apologies if this has been discussed before, I didn't find an indication that it'd been mentioned as a potential issue. Thanks for your time!

**Comment by Laevos** [comment]
Looking at [`default-release-rules.js`](https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js), it looks like there are some alternate forms which are accepted, including an all-caps `FEAT` and a title case `Fix`, but specifically _not_ a title case `Feat`. Would a case insensitive match make sense here? Potentially combined with https://github.com/semantic-release/commit-analyzer/pull/419, a case-insensitive regex could be used, so the rule could be a commit message which matches, say, `/^feat/i`?

**Comment by travi** [comment]
The key detail about the comment that you linked to is that semantic-release is configured to use the angular commit convention by default, not conventional-commits like your other reference. The angular convention is case sensitive. This is not a bug. If you want different rules, you need to use an alternative convention.
