### ISSUE TITLE
Use @commitlint/config-conventional with the new preset format

### ISSUE THREAD

**Issue by nicolas-goudry** [semantic-release/commit-analyzer#544]
Hello, I have an issue using the @commitlint/config-conventional config with semantic-release v22.

With v21, I was using the following configuration :

```json
{
  "branches": [
    "master",
    {
      "name": "develop",
      "prerelease": "beta"
    }
  ],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "config": "@commitlint/config-conventional",
        "releaseRules": [
          {
            "breaking": true,
            "release": "major"
          },
          {
            "type": "feat",
            "release": "minor"
          },
          {
            "type": "fix",
            "release": "patch"
          },
          {
            "type": "perf",
            "release": "patch"
          },
          {
            "type": "refactor",
            "release": "patch"
          },
          {
            "type": "revert",
            "release": "patch"
          },
          {
            "type": "style",
            "release": "patch"
          },
          {
            "type": "test",
            "release": false
          },
          {
            "type": "build",
            "release": false
          },
          {
            "type": "chore",
            "release": "patch"
          },
          {
            "type": "ci",
            "release": false
          },
          {
            "type": "docs",
            "release": false
          }
        ]
      }
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    [
      "@semantic-release/git",
      {
        "assets": [
          "package.json",
          "package-lock.json",
          "CHANGELOG.md"
        ]
      }
    ]
  ]
}
```

This was working fine until I updated to v22. I read the changelog and saw that the preset is using a new format, which is incompatible with the previous format used in v21.

However, I can’t find any documentation or guide on how I could keep using semantic-release with commitlint’s conventional config.

Could anyone please point me in the right direction ?

Thanks !

**Comment by travi** [comment]
in short, the preset needs to be updated to support the new format. it looks like this might be a start of that: https://github.com/conventional-changelog/commitlint/issues/3698

until the preset is updated, you will need to avoid updating to v22 of semantic-release

**Comment by nicolas-goudry** [comment]
Thanks for your answer, I’ll track the issue on commitlint repo and update to v22 when the preset gets updated then.

**Comment by travi** [comment]
sounds good. i'll close this issue at this point then, but feel free to comment here if anything more is needed from the semantic-release side
