### ISSUE TITLE
Document all presets

### ISSUE THREAD

**Issue by MartinMuzatko** [semantic-release/commit-analyzer#87]
Currently, the page https://github.com/conventional-changelog/conventional-changelog#plugins-supporting-conventional-changelog
only explains grunt, gulp and atom.

What about the other presets?
According to the readme, there are the following presets:

angular, atom, codemirror, ember, eslint, express, jquery, jscs, jshint

**Comment by pvdlg** [comment]
https://github.com/conventional-changelog/conventional-changelog is a different repository.

This of `preset` is mention in the description of the `preset` option here: https://github.com/semantic-release/commit-analyzer#options. And in anyway any preset can be supported via the `config` option that accept a npm package defining the preset as mentionned in the doc.

**Comment by MartinMuzatko** [comment]
I meant, what are the implications of every preset? I guess they are documented in their own repository. Linking to those would be nice then.

**Comment by pvdlg** [comment]
In the `preset` option there is already a link to [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) that contains the preset mentioned.

And it's impossible to give a link to every preset out there as it can be a npm package or js file created by anyone.

**Comment by MartinMuzatko** [comment]
@pvdlg I'll create a PR, and you decide to accept it or not :)
Thanks!

**Comment by pvdlg** [comment]
A PR to do what? I still don't see what is the problem you are reporting.

**Comment by MartinMuzatko** [comment]
@pvdlg I had no idea which convention these presets are following. And since there is no wiki and no link to them, I assumed to have only the source code in `packages`. So I added a PR to link to these docs, since they are hard to find.

**Comment by pvdlg** [comment]
I meant there is this link:
![semantic-release_commit-analyzer__customizable_commit_message_analyzer_plugin_for_semantic-release](https://user-images.githubusercontent.com/3250552/45001977-2f6b7600-afa0-11e8-96c4-d489dd2f0c13.jpg)

**Comment by MartinMuzatko** [comment]
Yes and that repo barely documents anything except for grunt/gulp/atom. Thats all.
