### ISSUE TITLE
Is there CLI alternative to commit-analyzer?

### ISSUE THREAD

**Issue by limonte** [semantic-release/commit-analyzer#89]
We have a custom script with some tricky steps which accepts the version number as an argument, something like this:

```
./custom-release-script.js 1.2.3
```

I would like to run that script from CI, and I need a tool which will do the same as `commit-analyzer` but standlalone, without `semantic-release`, something like

```
$ yarn what-is-the-next-release-version
1.2.3
```

Do you maybe know something like this?

PS. sorry for the kinda offtopic question, I'm not able to find the tool and I don't know the better place to ask :)

**Comment by pvdlg** [comment]
There is none provided by the semantic-release team.
Maybe you can look in this repo https://github.com/conventional-changelog/conventional-changelog or search on GitHub.
