### ISSUE TITLE
set parserOpts from external file

### ISSUE THREAD

**Issue by kariae** [semantic-release/commit-analyzer#93]
is it possible to set `parserOpts` from an external file, like `releaseRules`, cause you can't override the option `headerPattern` in the `package.json` since it's a regex expression ?

**Comment by pvdlg** [comment]
You can use regex if you configure semantic-release with a `release.config.js` file. See [Configuration](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md).

You can also create a [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset (something like [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular)) and pass it in the `config` options.

**Comment by pvdlg** [comment]
Didn't mean to close the issue.
If you are satisfied with the provided answer, fell free to close the issue.

**Comment by kariae** [comment]
Thanks for the feedback, the idea of creating a preset sounds interesting, is there any doc stuffs about that?

**Comment by pvdlg** [comment]
Not that I am aware of. But it's really simple and you have many examples in the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) repo.

**Comment by kariae** [comment]
Ah nice, thank Pierre.
